### ISSUE TITLE
plotGrotrian support for recombination lines

### ISSUE THREAD

**Issue by themiyan** [Morisset/PyNeb_devel#11]
is there a reason for plotGrotrian to not be supported for recombination lines?

**Comment by Morisset** [comment]
Hi,
In the RecAtom object, the levels are not defined, only the lines are known, with some transition probabilities to compute the emissivities. There is no way to build a Grotrian diagram in thiese conditions.
Hope it helps.
Christophe
PS: better use the Google group to ask questions, it is more visible than the PyNeb issues ;-)
https://groups.google.com/forum/#!forum/pyneb
