### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by MySlientWind** [Morisset/PyNeb_devel#21]
`help(pn.Atom.getEmissivity)` shows
```
Help on function getEmissivity in module pyneb.core.pynebcore:

getEmissivity(self, tem, den, lev_i=-1, lev_j=-1, wave=-1, product=True)
    Return the line emissivity (in erg.s-1.cm3) of selected transition or complete array of emissivities
    The transition is selected by the argument wave (if given); 
    if wave is not supplied, it is selected by the upper and lower levels (lev_i and lev_j); 
    if neither is given, the whole array is computed
    
    Usage:      
        O3.getEmissivity(12000, 100, 4, 2)         # (4, 2) transition
        O3.getEmissivity(10000, 10000, wave=5007)  # (4, 2) transition
        O3.getEmissivity(12000, 100)               # all transitions
        O3.getEmissivity([10000, 12000], [100, 500], 4, 2)
        O3.getEmissivity([10000, 12000], [100, 500])
        
    Parameters:
        - tem      electronic temperature in K. May be an array.
        - den      electronic density in cm^-3. May be an array.
        - lev_i    upper level (default= -1)
        - lev_j    lower level (default= -1)
        - wave     wavelength of transition. Takes precedence on lev_i and lev_j if set, 
                    ignored otherwise. It can also be a blend label.
        - product  Boolean. If True (default), all the combination of (tem, den) are used. 
                     If False, tem and den must have the same size and are joined.
```
I think the unit of emissivity should be erg.s-1.cm-3, so there is a typo or maybe my understanding was wrong.

**Comment by MySlientWind** [comment]
I have checked the code and found the "emissivity" returned by this method (e_code) is not actually the "emissivity" in equation 2 of V. Luridiana , C. Morisset , and R. A. Shaw 2015 (e_paper). 
The relation between these two "emissivity" are: **e_code = e_paper/(n_e * n_ion)**
I think it is better to metion it in document, really a bit confused.

**Comment by Morisset** [comment]
Hi,
The emissivities obtained by getEmissivity are in erg.s-1.cm3, as specified in the docstring of the method. The volume emission (erg.s-1.cm-3) is obtained by multiplying this emissivity by N_e.N_Xi (the product of the electron and the ion abundances).
I do not see contradiction with the eq. 3 of the Luridiana et al paper. In this equation, n_j is the level population, not density.
Hope it helps,
Christophe

**Comment by MySlientWind** [comment]
> Hi, The emissivities obtained by getEmissivity are in erg.s-1.cm3, as specified in the docstring of the method. The volume emission (erg.s-1.cm-3) is obtained by multiplying this emissivity by N_e.N_Xi (the product of the electron and the ion abundances). I do not see contradiction with the eq. 3 of the Luridiana et al paper. In this equation, n_j is the level population, not density. Hope it helps, Christophe

Oh, I see. Thanks for your reply, I'm new to emission line analysis and sorry for my misunderstanding.
